name: tests

on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up python venv
        run: |
          python${{ matrix.python-version }} -m venv ~/pyenv

      - name: Checkout anki-tests
        uses: actions/checkout@v2

      - name: Checkout anki
        uses: actions/checkout@v2
        with:
          repository: dae/anki
          path: anki_root

      - name: Install anki dependencies
        working-directory: anki_root
        run: |
          sudo apt-get install portaudio19-dev
          . ~/pyenv/bin/activate
          pip install --upgrade setuptools pip
          pip install -r requirements.txt
          pip install -r requirements.qt

      - name: Set up node build dependency for anki
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up protoc build dependency for anki
        uses: Arduino/actions/setup-protoc@master

      - name: Build anki
        working-directory: anki_root
        run: |
          make build

      - name: Install xvfb and its dependencies
        run: |
          sudo apt-get install xvfb libxkbcommon-x11-0

      - name: Install anki-tests and its dependencies
        run: |
          . ~/pyenv/bin/activate
          pip install .

      - name: Run tests
        run: |
          . ~/pyenv/bin/activate
          ./tools/run_tests.sh
